// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://asbpgelqanuwmqdasbbd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzYnBnZWxxYW51d21xZGFzYmJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwMDA2NTUsImV4cCI6MjA1NzU3NjY1NX0.R242Ii0JyhZFZiWZXmCjH6NDaQO-rHICy0aphTiQ6wE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);